parameters:
- name: jobName
  default: ''
- name: databaseName
  default: ''
- name: databasePostfix
  default: '_DEV'
- name: artifactName
  default: 'DatabaseArtifacts'  
- name: vmImage
  default: 'ubuntu-16.04'  
- name: containerImage
  default: 'kulmam92/flyway-azure:6.2.3'
- name: environmentName
  default: 'DEV'
- name: flywayCommand
  default: 'info'

jobs:
- job: ${{ parameters.jobName }}
  timeoutInMinutes: 10
  pool:
    vmImage: ${{ parameters.vmImage }}
  container:
    image: ${{ parameters.containerImage }}      
  steps:
  - bash: |
      echo "##vso[task.setvariable variable=SNOWFLAKE_JDBC_URL]$(SNOWFLAKE_JDBC_URL)$(SNOWFLAKE_ACCOUNT_NAME)/?warehouse=$(SNOWFLAKE_WAREHOUSE)&role=$(SNOWFLAKE_ROLENAME)&authenticator=$(SNOWFLAKE_AUTHENTICATOR)"
    name: Construct_JDBC_URL
  - script: flyway -url='$(SNOWFLAKE_JDBC_URL)&db=${{ parameters.databaseName }}${{ parameters.databasePostfix }}' -user=$(SNOWFLAKE_DEVOPS_USERNAME) -password=$(SNOWFLAKE_DEVOPS_SECRET) -locations='filesystem:./databases/${{ parameters.databaseName }}' ${{ parameters.flywayCommand }}
    name: Run_flyway_Command